# Generated by Django 5.1.1 on 2024-09-24 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='conclusion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='development',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project'),
        ),
    ]
