# Generated by Django 5.1.1 on 2024-09-25 11:49

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    for project in Project.objects.all():
        if not project.slug:
            base_slug = slugify(project.title)
            slug = base_slug
            num = 1
            while Project.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{num}"
                num += 1
            project.slug = slug
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='development',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
