name: Tests

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
          CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          DB_NAME: ${{ secrets.DB_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
        
    - name: Debug Environment Variables
      run: |
        echo "DB_NAME=${{ secrets.DB_NAME }}"
        echo "DB_USER=${{ secrets.DB_USER }}"
        echo "DB_HOST=${{ secrets.DB_HOST }}"
        echo "DB_PORT=${{ secrets.DB_PORT }}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        
    - name : Lint with flake8
      run: |
        flake8
        
    - name: Coverage report  
      run: |
        coverage run manage.py test
        
    - name: Django Testing
      run: |
        python3 manage.py test
